### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by lechatdeschats** [nulli0n/AdvancedMobArena-spigot#14]
hello, I have a problem when I want to load the plugins it remains in red and in error

error : 
[12:47:16 ERROR]: Error occurred while enabling AdvancedMobArena v7.10.0 (Is it up to date?)
java.lang.IllegalStateException: Invalid entity type for 'frog' mob!
        at su.nightexpress.ama.mob.config.MobConfig.load(MobConfig.java:88) ~[AdvancedMobArena-7.10.0.jar:?]
        at su.nightexpress.ama.mob.MobManager.onLoad(MobManager.java:51) ~[AdvancedMobArena-7.10.0.jar:?]
        at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:20) ~[NexEngine.jar:?]
        at su.nightexpress.ama.AMA.enable(AMA.java:121) ~[AdvancedMobArena-7.10.0.jar:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:215) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

server version : 
This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2) You are running the latest version

protcolib version : 
ProtocolLib 5.1.0

nexengine version : 
nexEngine 2.2.12 

AdvancedMobArena version : 
AdvancedMobArena 7.10.0

**Comment by nulli0n** [comment]
Remove 'frog' mob from the /mobs/ folder.
