### ISSUE TITLE
Error while loading plugin

### ISSUE THREAD

**Issue by Neyji** [nulli0n/AdvancedMobArena-spigot#15]
Hello I am getting an error while starting the server that disables the plugin

```
[16:30:36 ERROR]: Error occurred while enabling AdvancedMobArena v7.11.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'su.nexmedia.engine.api.editor.EditorLocales$Builder su.nexmedia.engine.api.editor.EditorLocales$Builder.emptyLine()'
        at su.nightexpress.ama.editor.EditorLocales.<clinit>(EditorLocales.java:31) ~[AdvancedMobArena-7.11.0.jar:?]
        at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
        at jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:140) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176) ~[?:?]
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1169) ~[?:?]
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1148) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:426) ~[?:?]
        at su.nexmedia.engine.lang.LangManager.loadEditor(LangManager.java:213) ~[NexEngine.jar:?]
        at su.nightexpress.ama.AMA.loadLang(AMA.java:191) ~[AdvancedMobArena-7.11.0.jar:?]
        at su.nexmedia.engine.NexPlugin.setupLangManager(NexPlugin.java:183) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:195) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The Server is running on Minecraft version 1.20.1 and the latest Purpur version for that version
Other Plugins on the Server are ProtocolLib 5.1.0, NexEngine 2.2.12 and spark

AdvancedMobArena version is 7.11.0

**Comment by nulli0n** [comment]
Redownload NexEngine
