### ISSUE TITLE
[bug] Can not use the plugin!

### ISSUE THREAD

**Issue by chasiopen** [nulli0n/AdvancedMobArena-spigot#18]
server : arclight-forge-1.18.2-1.0.10
NexEngine: newest

plugin version: 7.15.0
[AdvancedMobArena]: Could not setup NMS interface! (Unsupported server version)

If use AMA 7.14.0,
[AdvancedMobArena]: Task #3341 for AdvancedMobArena v7.14.0 generated an exception
java.lang.NullPointerException: Cannot invoke "su.nightexpress.ama.arena.ArenaManager.plugin()" because "arenaManager" is null
        at su.nightexpress.ama.arena.editor.arena.ArenaListEditor.<init>(ArenaListEditor.java:32) ~[?:?]
        at su.nightexpress.ama.editor.EditorHub.getArenaEditor(EditorHub.java:46) ~[?:?]
        at su.nightexpress.ama.editor.EditorHub.lambda$new$0(EditorHub.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[arclight-1.18.2-1.0.10-033f7507.jar%2370!/:arclight-1.18.2-1.0.10-033f7507]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) ~[arclight-1.18.2-1.0.10-033f7507.jar%2370!/:arclight-1.18.2-1.0.10-033f7507]
        at net.minecraft.server.MinecraftServer.handler$zpb000$arclight$runScheduler(MinecraftServerMixin.java:2381) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

PLZ fix it!

**Comment by dinobossytnew** [comment]
Only use other non-hybrid software, use paper spigot, spigot, purpur.

**Comment by nulli0n** [comment]
Yes, modded severs are not supported because of their internal changes, nothing I can do to fix that.
