### ISSUE TITLE
Plugin not correctly initialized

### ISSUE THREAD

**Issue by J4im3x0** [nulli0n/AdvancedMobArena-spigot#22]
NexEngine v2.2.12
Server version: git-Paper-431 (MC: 1.20.4)

`[14:41:15] [Server thread/INFO]: [AdvancedMobArena] Enabling AdvancedMobArena v7.16.0
[14:41:15] [Server thread/INFO]: [AdvancedMobArena] Powered by: NexEngine
[14:41:15] [Server thread/WARN]: [AdvancedMobArena] ==================================
[14:41:15] [Server thread/WARN]: [AdvancedMobArena] WARNING: You're running an outdated/deprecated server version (Unknown)!
[14:41:15] [Server thread/WARN]: [AdvancedMobArena] Support for this version will be dropped soon.
[14:41:15] [Server thread/WARN]: [AdvancedMobArena] Please, upgrade your server to at least 1.18.2.
[14:41:15] [Server thread/WARN]: [AdvancedMobArena] ==================================
[14:41:15] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: ama [7.16.0]
[14:41:15] [Server thread/INFO]: [AdvancedMobArena] Registered mob provider: MythicMobs
[14:41:15] [Server thread/INFO]: [AdvancedMobArena] Registered pet provider: MCPets
[14:41:15] [Server thread/ERROR]: Error occurred while enabling AdvancedMobArena v7.16.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'su.nexmedia.engine.api.editor.EditorLocales$Builder su.nexmedia.engine.api.editor.EditorLocales$Builder.emptyLine()'
	at su.nightexpress.ama.editor.EditorLocales.<clinit>(EditorLocales.java:32) ~[AdvancedMobArena-7.16.0.jar:?]
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
	at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185) ~[?:?]
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132) ~[?:?]
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1113) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
	at su.nexmedia.engine.lang.LangManager.loadEditor(LangManager.java:213) ~[NexEngine.jar:?]
	at su.nightexpress.ama.AMA.loadLang(AMA.java:191) ~[AdvancedMobArena-7.16.0.jar:?]
	at su.nexmedia.engine.NexPlugin.setupLangManager(NexPlugin.java:183) ~[NexEngine.jar:?]
	at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:195) ~[NexEngine.jar:?]
	at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[NexEngine.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-430]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-430]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-430]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-430]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:41:15] [Server thread/INFO]: [AdvancedMobArena] Disabling AdvancedMobArena v7.16.0
[14:41:15] [Server thread/ERROR]: Error occurred while disabling AdvancedMobArena v7.16.0
java.lang.NullPointerException: Cannot invoke "su.nexmedia.engine.api.data.AbstractUserManager.shutdown()" because the return value of "su.nexmedia.engine.api.data.UserDataHolder.getUserManager()" is null
	at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:236) ~[NexEngine.jar:?]
	at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:84) ~[NexEngine.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-430]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-430]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:git-Paper-430]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-430]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-430]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-430]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-430]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by LadyHaley** [comment]
Make sure your nexengine version is the latest one, theres a few with the version number 2.2.12, the latest one adding support for 1.12.4
https://github.com/nulli0n/NexEngine-spigot/releases

**Comment by J4im3x0** [comment]
> Make sure your nexengine version is the latest one, theres a few with the version number 2.2.12, the latest one adding support for 1.12.4 https://github.com/nulli0n/NexEngine-spigot/releases

![image](https://github.com/nulli0n/AdvancedMobArena-spigot/assets/36940599/02debf2d-2ad2-4abb-befd-9d151bd020ea)
Is the latest one
